### ISSUE TITLE
AWS Elasticsearchservice : Issue with save (refresh does not have the right acces keys)

### ISSUE THREAD

**Issue by seustachi** [spring-projects/spring-data-elasticsearch#1901]
Calling AWS Elasticsearch Service, we have an error when calling, save, delete etc .....

The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The first call to actually save or delete is succesful (200), but then a call to refresh the index is made, and I assume this call does not have the signing parameters properly configured, because we get a 403.

```
org.springframework.data.elasticsearch.UncategorizedElasticsearchException: Unable to parse response body; nested exception is ElasticsearchStatusException[Unable to parse response body]; nested: ResponseException[method [POST], host [https://search-dev2-elasticsearch-jobook-d2bx2g4enadlcx5nyzoi4fnntq.eu-central-1.es.amazonaws.com], URI [/jobs/_refresh?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true], status line [HTTP/1.1 403 Forbidden]
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}];
	at org.springframework.data.elasticsearch.core.ElasticsearchExceptionTranslator.translateExceptionIfPossible(ElasticsearchExceptionTranslator.java:66)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.translateException(ElasticsearchRestTemplate.java:402)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:385)
	at org.springframework.data.elasticsearch.core.DefaultIndexOperations.doRefresh(DefaultIndexOperations.java:213)
	at org.springframework.data.elasticsearch.core.AbstractDefaultIndexOperations.refresh(AbstractDefaultIndexOperations.java:174)
	at org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository.doRefresh(SimpleElasticsearchRepository.java:312)
	at org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository.executeAndRefresh(SimpleElasticsearchRepository.java:360)
	at org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository.save(SimpleElasticsearchRepository.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by sothawo** [comment]
How do you do the request signing?

**Comment by seustachi** [comment]
We have the following : 

```
 @Bean
    public RestHighLevelClient elasticsearchClient() {
        credentialsProvider = awsCredentialsConfiguration.awsDynamoCredentialsProviderDevelopment();
        AWS4Signer signer = new AWS4Signer();
        String serviceName = "es";
        signer.setServiceName(serviceName);
        signer.setRegionName(region);
        HttpRequestInterceptor interceptor = new AWSRequestSigningApacheInterceptor(serviceName, signer, credentialsProvider);
        return new RestHighLevelClient(RestClient.builder(HttpHost.create(endpoint)).setHttpClientConfigCallback(e -> e.addInterceptorLast(interceptor)));
    }
```

and : 

```
public class AWSCredentialsConfiguration {

	@Value("#{systemEnvironment['AWS_ACCESS_KEY_ID']}")
    private String esAccessKey = null;

	@Value("#{systemEnvironment['AWS_SECRET_ACCESS_KEY']}")
    private String esSecretKey = null;

    @Bean
    public AWSStaticCredentialsProvider awsDynamoCredentialsProviderDevelopment() {
        return new AWSStaticCredentialsProvider(new BasicAWSCredentials(
                esAccessKey, esSecretKey));
    }

//    @Bean
    public AWSCredentialsProvider amazonAWSCredentialsProvider() {
        return new EC2ContainerCredentialsProviderWrapper();
    }
```

We used to use the EC2ContainerCredentialsProviderWrapper but found out the AWSStaticCredentialsProvider would also work for our unit tests.

Thanks !

**Comment by sothawo** [comment]
I'd recommend to create a configuration like it is described in the documentation athttps://docs.spring.io/spring-data/elasticsearch/docs/4.2.4/reference/html/#elasticsearch.clients.rest and https://docs.spring.io/spring-data/elasticsearch/docs/4.2.4/reference/html/#elasticsearch.clients.configuration, you can use the httpClient configuration callback to ass the interceptor.

The better point of using this configuration is that you can override `RefreshPolicy refreshPolicy()` in your configuration class and set a refresh policy. If this is set, the `SimpleElasticsearchRepository` will not do the additional refresh call to the service, but pass the desired refresh parameter in the insert/update/delete call.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
