### ISSUE TITLE
IndexOutOfBoundsException when try to map inner hits with no results returned

### ISSUE THREAD

**Issue by xhaggi** [spring-projects/spring-data-elasticsearch#1997]
Configuring `inner_hits` with a size of 0 will result in an `IndexOutOfBoundsException` when mapping inner hits.

```
WARN  o.s.d.e.core.SearchHitMapping - Could not map inner_hits
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.springframework.data.elasticsearch.core.SearchHitsImpl.getSearchHit(SearchHitsImpl.java:97)
	at org.springframework.data.elasticsearch.core.SearchHitMapping.mapInnerDocuments(SearchHitMapping.java:181)
	at org.springframework.data.elasticsearch.core.SearchHitMapping.mapInnerHits(SearchHitMapping.java:158)
	at org.springframework.data.elasticsearch.core.SearchHitMapping.mapHit(SearchHitMapping.java:115)
	at org.springframework.data.elasticsearch.core.SearchHitMapping.mapHitsFromResponse(SearchHitMapping.java:95)
	at org.springframework.data.elasticsearch.core.SearchHitMapping.mapHits(SearchHitMapping.java:71)
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate$ReadSearchDocumentResponseCallback.doWith(AbstractElasticsearchTemplate.java:875)
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate$ReadSearchDocumentResponseCallback.doWith(AbstractElasticsearchTemplate.java:860)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.search(ElasticsearchRestTemplate.java:299)
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.search(AbstractElasticsearchTemplate.java:513)
	at ch.x28.jobportal.core.searchindex.SearchIndexRepositoryImpl.findAll(SearchIndexRepositoryImpl.java:56)
```

**Comment by AntonLGVS** [comment]
This is thrown out here:
**org.springframework.data.elasticsearch.core.SearchHitMapping#mapInnerDocuments**
`[line:202] NestedMetaData nestedMetaData = searchHits.getSearchHit(0).getContent().getNestedMetaData();`

**Comment by xhaggi** [comment]
@AntonLGVS the stacktrace is clear enough to know what the root cause is. I have already created a pull request and fixed this problem.

**Comment by sothawo** [comment]
backported to 4.3. Did not backport to 4.2 and 4.1 because the test cannot be backported there as `NativeSearchQueryBuilder.withCollapseBuilder` was introduced in 4.3

**Comment by xhaggi** [comment]
IMO we should adjust the test for 4.2, 4.1 because the issue also exists in these versions.

**Comment by xhaggi** [comment]
We could use a nested query with inner hits [1] instead of collapse to test the issue.

[1] https://www.elastic.co/guide/en/elasticsearch/reference/7.16/inner-hits.html#nested-inner-hits

**Comment by sothawo** [comment]
Can you please cherrypick the commit from 4.3 to 4.2 and adjust the test then? And then further cherrypick from 4.2 to 4.1?

**Comment by xhaggi** [comment]
Sure will do that tomorrow.

**Comment by xhaggi** [comment]
Backported to 4.2.x and 4.1.x.

**Comment by sothawo** [comment]
thanks a lot
