### ISSUE TITLE
Issue with spring-data-elasticsearch 4.3 and Elasticsearch 7.10

### ISSUE THREAD

**Issue by maazhe** [spring-projects/spring-data-elasticsearch#2021]
Hi,

We recently migrate our application to spring-boot-starter-parent v 2.6.1 with spring-data-elasticsearch v 4.3.
Unfortunately we use AWS ElasticSearch Service with ES v 7.10, which seems to be not compatible now. 

I saw this in logs:

```
web: org.springframework.data.elasticsearch.UncategorizedElasticsearchException: Invalid or missing build flavor [oss]; nested exception is ElasticsearchException[Invalid or missing build flavor [oss]]
...
...
Caused by: org.elasticsearch.ElasticsearchException: Invalid or missing build flavor [oss]
at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2084)
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1732)
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1702)
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1672)
at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1128)
at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.lambda$search$11(ElasticsearchRestTemplate.java:317)
at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:408)
... 59 common frames omitted
```

Is there any way to have a compatibility between them?
Maybe we should downgrade version of spring-data-elasticsearch to 4.2.6?

Thanks

**Comment by sothawo** [comment]
Elasticsearch introduced this check in 7.14 I think. I did not find it in the code for the `RestHighLevelClient` in version 7.12.1 that is used by Spring Data Elasticsearch 4.2.7.

You can try to downgrade to SDE 4.2.7, but this might yield problems with the spring-data common module that is pulled in from the Spring Boot bom. You'll have to try.

**Comment by maazhe** [comment]
We downgraded all spring-data-parent to 2.5.7, with spring-data-elastic-search 4.2.7

All seems to be working for now.

Just to know, will you be compatible with Opensearch 1.0 (derived from ES 7.10 ) (it's provided as an upgrade of ES  by AWS7.10 from now)

**Comment by maazhe** [comment]
Thank you for your answer, I'll continue to check the new versions as well
