### ISSUE TITLE
RequestFactory.toElasticsearchIndicesOptions fails on empty options or wildcard states

### ISSUE THREAD

**Issue by pnowak85** [spring-projects/spring-data-elasticsearch#2075]
If you try to create custom [IndicesOptions](https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/main/java/org/springframework/data/elasticsearch/core/query/IndicesOptions.java) with either an empty set of [Option](https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/main/java/org/springframework/data/elasticsearch/core/query/IndicesOptions.java#L86) or [WildcardState](https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/main/java/org/springframework/data/elasticsearch/core/query/IndicesOptions.java#L82) you get an `IllegalArgumentException`: 
```
java.lang.IllegalArgumentException: Collection is empty

	at java.util.EnumSet.copyOf(EnumSet.java:174)
	at org.springframework.data.elasticsearch.core.RequestFactory.toElasticsearchIndicesOptions(RequestFactory.java:1696)
```

The empty `Option` or `WildcardState` should be allowed, as for example the default [STRICT_SINGLE_INDEX_NO_EXPAND_FORBID_CLOSED ](https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/main/java/org/springframework/data/elasticsearch/core/query/IndicesOptions.java#L65) IndicesOption has an empty set of `WildcardState` and therefor fails if you use it.

I have a working fix (and test), will create a MR once i have resolved my upstream conflicts :D

**Comment by pnowak85** [comment]
backport to 4.3.x would be nice, as we are currently facing this issue in 4.3.1
