### ISSUE TITLE
Extending org.springframework.data.elasticsearch.client.elc.ElasticsearchConfiguration required dependency to org.springframework.web.reactive.function.client.WebClient

### ISSUE THREAD

**Issue by rtambun** [spring-projects/spring-data-elasticsearch#2189]
I am moving Elasticsearch configuration to use new ElasticsearchClient by extending ElasticsearchConfiguration according to ElasticsearchConfigurationELCTests. (I am using spring-boot-starter-data-elasticsearch:2.7.0)

This is my class, 

`
@Configuration
@EnableElasticsearchRepositories(basePackages = "com.rtambun.minio.repository")
public class ElasticSearchConfiguration extends ElasticsearchConfiguration {

    private final String elasticSearchHost;
    private final int elasticSearchPort;
    private final String elasticSearchUserName;
    private final String elasticSearchPassword;

    public ElasticSearchConfiguration(@Value("${elasticsearch.host}") String elasticSearchHost,
                                      @Value("${elasticsearch.port}") int elasticSearchPort,
                                      @Value("${elasticsearch.username}") String elasticSearchUserName,
                                      @Value("${elasticsearch.password}") String elasticSearchPassword) {
        this.elasticSearchHost = elasticSearchHost;
        this.elasticSearchPort = elasticSearchPort;
        this.elasticSearchUserName = elasticSearchUserName;
        this.elasticSearchPassword = elasticSearchPassword;
    }

    @Override
    @Nonnull
    public ClientConfiguration clientConfiguration() {
        if (elasticSearchUserName != null && !elasticSearchUserName.isBlank()
                && elasticSearchPassword != null && !elasticSearchPassword.isBlank()) {
            return ClientConfiguration.builder()
                    .connectedTo(String.format("%s:%s", elasticSearchHost, elasticSearchPort))
                    .withBasicAuth(elasticSearchUserName, elasticSearchPassword)
                    .build();
        } else {
            return ClientConfiguration.create(String.format("http://%s:%s", elasticSearchHost, elasticSearchPort));
        }
    }
}
`

And when i run i get following error: 
`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clientConfiguration' defined in class path resource [com/rtambun/minio/config/ElasticSearchConfiguration.class]: Initialization of bean failed; nested exception is java.lang.TypeNotPresentException: Type org.springframework.web.reactive.function.client.WebClient not present
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at app//org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at app//org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at app//org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)`

Once i add reference to org.springframework.web.reactive.function.client.WebClient on my gradle.build it is working. It will be nice if spring-boot-starter-data-elasticsearch include the library, so extending ElasticsearchConfiguration will be working out of the box.

**Comment by sothawo** [comment]
The configuration does not require the `WebClient`. The `WebClient` was needed by the old reactive implementation, the new one doesn't need it anymore as well.

Have you read the [documentation about the new client setup](https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch-migration-guide-4.3-4.4.new-clients)?

**Comment by rtambun** [comment]
Thanks for the feedback. I am checking the document and i don't have the issue anymore.
