### ISSUE TITLE
unable to use @Field(type = FieldType.Date, format = DateFormat.date)

### ISSUE THREAD

**Issue by wszpwsren** [spring-projects/spring-data-elasticsearch#2229]
dependencies:

java1.8
spring-boot 2.3.12
spring-data-elasticsearch 4.3.5

i'm writing a docment that contain a date variable like '2022-07-19'
so i use annotation @Field(type = FieldType.Date, format = DateFormat.date) on it 

```
    @Field(type = FieldType.Date, format = DateFormat.date)
    private Date createTime;
```

when reading data it came out an exception

```
        org.springframework.data.elasticsearch.core.convert.ConversionException: Unable to convert value '2022-07-19' to java.util.Date for property 'createTime'

        at org.springframework.data.elasticsearch.core.convert.DatePropertyValueConverter.read(DatePropertyValueConverter.java:54) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]
        at org.springframework.data.elasticsearch.core.convert.MappingElasticsearchConverter$Reader.convertOnRead(MappingElasticsearchConverter.java:490) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]
        at org.springframework.data.elasticsearch.core.convert.MappingElasticsearchConverter$Reader.propertyConverterRead(MappingElasticsearchConverter.java:484) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]
        at org.springframework.data.elasticsearch.core.convert.MappingElasticsearchConverter$Reader.readValue(MappingElasticsearchConverter.java:430) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]
        at org.springframework.data.elasticsearch.core.convert.MappingElasticsearchConverter$Reader$ElasticsearchPropertyValueProvider.getPropertyValue(MappingElasticsearchConverter.java:634) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]
        at org.springframework.data.elasticsearch.core.convert.MappingElasticsearchConverter$Reader.readProperties(MappingElasticsearchConverter.java:409) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]
        at org.springframework.data.elasticsearch.core.convert.MappingElasticsearchConverter$Reader.readEntity(MappingElasticsearchConverter.java:332) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]
        at org.springframework.data.elasticsearch.core.convert.MappingElasticsearchConverter$Reader.read(MappingElasticsearchConverter.java:262) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]
        at org.springframework.data.elasticsearch.core.convert.MappingElasticsearchConverter$Reader.read(MappingElasticsearchConverter.java:221) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]
        at org.springframework.data.elasticsearch.core.convert.MappingElasticsearchConverter.read(MappingElasticsearchConverter.java:165) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]
        at org.springframework.data.elasticsearch.core.convert.MappingElasticsearchConverter.read(MappingElasticsearchConverter.java:88) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]
        at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate$ReadDocumentCallback.doWith(AbstractElasticsearchTemplate.java:732) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_292]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_292]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_292]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_292]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_292]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_292]
        at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate$ReadSearchDocumentResponseCallback.doWith(AbstractElasticsearchTemplate.java:761) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]
        at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate$ReadSearchDocumentResponseCallback.doWith(AbstractElasticsearchTemplate.java:746) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]
        at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.search(ElasticsearchRestTemplate.java:322) ~[spring-data-elasticsearch-4.3.6.jar!/:4.3.6]

```

and i found that function catched an exception 

```

Exception in thread     java.time.format.DateTimeParseException: Text '2022-07-19' could not be parsed: Unable to obtain LocalDateTime from TemporalAccessor: {},ISO resolved to 2022-07-19 of type java.time.format.Parsed
	at java.base/java.time.format.DateTimeFormatter.createError(DateTimeFormatter.java:2017)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1952)
	at org.springframework.data.elasticsearch.core.convert.ElasticsearchDateConverter$PatternDateFormatter.parse(ElasticsearchDateConverter.java:354)
	at org.springframework.data.elasticsearch.core.convert.ElasticsearchDateConverter.parse(ElasticsearchDateConverter.java:131)

```

it's a bug or i made it with wrong environment?

**Comment by sothawo** [comment]
`java.util.Date` is an instant in time in the UTC timezone, besides the date it has a time and a timezone (UTC). This cannot be instantiated from a local date like "2022-07-19".

You should stop using the old `java.util.Date` class, Java 8 introduced the `java.time` package 8 years ago to overcome the many problems that `java.util.Date` has.

If your dates are of the format "uuuu-MM-dd" (that's `DateFormat.date`) the appropriate type in your entity would probably be `LocalDate`. If you want to represent an instant in time using `Instant` (or the old problematic `java.util.Date`) then  you should choose a date format that can handle time and zone as well in addition to the date like `DateFormat.date_time`

**Comment by wszpwsren** [comment]
> `java.util.Date` is an instant in time in the UTC timezone, besides the date it has a time and a timezone (UTC). This cannot be instantiated from a local date like "2022-07-19".
> 
> You should stop using the old `java.util.Date` class, Java 8 introduced the `java.time` package 8 years ago to overcome the many problems that `java.util.Date` has.
> 
> If your dates are of the format "uuuu-MM-dd" (that's `DateFormat.date`) the appropriate type in your entity would probably be `LocalDate`. If you want to represent an instant in time using `Instant` (or the old problematic `java.util.Date`) then you should choose a date format that can handle time and zone as well in addition to the date like `DateFormat.date_time`

thanks, i have the problem fixed
