### ISSUE TITLE
NPE in ElasticsearchExceptionTranslator

### ISSUE THREAD

**Issue by ztomic** [spring-projects/spring-data-elasticsearch#2388]
Hi,

I'm migrating from Spring Boot 2.7 to Spring Boot 3 and switching to new Spring Data Elasticsearch.

I have many problems with it (most of them with rewriting queries and aggregations from old to new Spring Data - since `QueryBuilders` class from here is missing queries, I must mix it with `QueryBuilders` from ES client and direct builders for query/aggregations from ES client -  it is not the happiest solution that the  `QueryBuilders` class in Spring Data Elasticsearch is named the same as in the ES client, and at many places I need to use `._toQuery()` from `QueryVariant`)

Back to the topic, `ElasticsearchExceptionTranslator` is generating `NullPointerException` because `ErrorResponse.error().type() is null`:
![image](https://user-images.githubusercontent.com/1428972/205597423-2c0dd58c-3070-4dc5-b1b0-9cba898a19b4.png)

![image](https://user-images.githubusercontent.com/1428972/205595564-bc5bb1b3-984a-45ff-9bbd-ea9fce06fc98.png)

```log
Caused by: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "co.elastic.clients.elasticsearch._types.ErrorCause.type()" is null
	at org.springframework.data.elasticsearch.client.elc.ElasticsearchExceptionTranslator.translateExceptionIfPossible(ElasticsearchExceptionTranslator.java:91)
	at org.springframework.data.elasticsearch.client.elc.ElasticsearchExceptionTranslator.translateException(ElasticsearchExceptionTranslator.java:62)
	at org.springframework.data.elasticsearch.client.elc.ChildTemplate.execute(ChildTemplate.java:73)
```

**Comment by sothawo** [comment]
Thanks for reporting that NPE, fixed in _main_ and I wll as well backport it to 5.0.x.

As for the name clashing of `QueryBuilders`: I'll add a ticket to have this renamed in 5.1.

**Comment by ztomic** [comment]
Thanks!

**Comment by ztomic** [comment]
@sothawo when using `Critera`, how can we use `Aggregation` with it? Currently only possible solution as I can see is to copy `CriteriaQueryProcessor` (since it is package private) and use it's `createQuery` method and then use `NativeQueryBuilder`.

**Comment by sothawo** [comment]
Currently it is not possible. The problem with building the Elasticsearch Query and copying this is that this needs the Entity of the query for fieldname mapping or property converters which normally not used at the Spring Data Elasticsearch query creation level.

But it might be possible to add a Spring Data Elasticsearch instead of an Elasticsearch query into a `NativeQuery` and use that when the `NativeQuery` is processed. This would make only sense for `StringQuery` or `CriteriaQeury` and not for `NativeQuery` objects to be put in there. I created #2391 for this.

**Comment by ztomic** [comment]
That will be great, thanks!
