### ISSUE TITLE
RequestConverter.getQuery : IllegalArgumentException unhandled Query implementation org.springframework.data.elasticsearch.core.query.NativeSearchQuery

### ISSUE THREAD

**Issue by slide2009** [spring-projects/spring-data-elasticsearch#2396]
Hello Team,
I am using spring-data-elasticsearch 4.4.6.
When I use ElasticsearchTemplate.multiSearch with a List<NativeSearchQuery> as argument RequestConverter throws an IllegalArgumentException. Here the log :
```
Caused by: java.lang.IllegalArgumentException: unhandled Query implementation org.springframework.data.elasticsearch.core.query.NativeSearchQuery
	at org.springframework.data.elasticsearch.client.elc.RequestConverter.getQuery(RequestConverter.java:1344) ~[spring-data-elasticsearch-4.4.6.jar:4.4.6]
	at org.springframework.data.elasticsearch.client.elc.RequestConverter.lambda$null$56(RequestConverter.java:1071) ~[spring-data-elasticsearch-4.4.6.jar:4.4.6]
	at co.elastic.clients.elasticsearch.core.msearch.RequestItem$Builder.body(RequestItem.java:151) ~[elasticsearch-java-7.17.7.jar:na]
	at org.springframework.data.elasticsearch.client.elc.RequestConverter.lambda$null$57(RequestConverter.java:1070) ~[spring-data-elasticsearch-4.4.6.jar:4.4.6]
	at co.elastic.clients.elasticsearch.core.MsearchRequest$Builder.searches(MsearchRequest.java:528) ~[elasticsearch-java-7.17.7.jar:na]
	at org.springframework.data.elasticsearch.client.elc.RequestConverter.lambda$null$58(RequestConverter.java:1065) ~[spring-data-elasticsearch-4.4.6.jar:4.4.6]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
	at org.springframework.data.elasticsearch.client.elc.RequestConverter.lambda$searchMsearchRequest$59(RequestConverter.java:1062) ~[spring-data-elasticsearch-4.4.6.jar:4.4.6]
	at co.elastic.clients.elasticsearch.core.MsearchRequest.of(MsearchRequest.java:121) ~[elasticsearch-java-7.17.7.jar:na]
	at org.springframework.data.elasticsearch.client.elc.RequestConverter.searchMsearchRequest(RequestConverter.java:1061) ~[spring-data-elasticsearch-4.4.6.jar:4.4.6]
	at org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate.doMultiSearch(ElasticsearchTemplate.java:436) ~[spring-data-elasticsearch-4.4.6.jar:4.4.6]
	at org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate.multiSearch(ElasticsearchTemplate.java:393) ~[spring-data-elasticsearch-4.4.6.jar:4.4.6]
	at fr.insee.csns.batch.processor.RechercheElasticProcessor.rechercher(RechercheElasticProcessor.java:91) ~[classes/:na]
	... 7 common frames omitted
```

Is there a way to get around this problem ?
Thank you for your help !

**Comment by sothawo** [comment]
You are using the class `org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate`, that's the implementation that under the hood uses the new Elasticsearch client. In 4.4.6 this is an optional alternative, in 5.0 this became the default implementation of `ElasticsearchOperations`

When using the `ElasticsearchTemplate` class with native queries, you need to pass in `NativeQuery` objects. These can be built with the `NativeQueryBuilder` and the classes from the new Elasticsearch client.

`NativeSearchQuery` is the class to be used with the `ElasticsearchRestTemplate` that uses the deprecated `RestHighlevelClient` from Elasticsearch.

The `NativeSearchQuery` and `NativeQuery` objects are not compatible.

**Comment by slide2009** [comment]
Thank you for your response.
Effectively I used ElasticsearchRestTemplate. I wanted to get rid of the deprecated RestHighLevelClient and replace it with the new ElasticsearchClient. By doing so I had to replace ElasticsearchRestTemplate with ElasticsearchTemplate. The call of ElasticsearchRestTemplate is like this : 
```java
List<Query> queries = new ArrayList<>();
NativeSearchQuery query = new NativeSearchQueryBuilder().withQuery(MyUtilitiesES.getQuery(individu)).withSourceFilter(SOURCE_FILTER).build()
queries.add(query);
List<SearchHits<IndividuIndex>> results = elasticsearchTemplate.multiSearch(queries, IndividuIndex.class,
                    IndexCoordinates.of(Constante.NOM_ALIAS_INDEX));
```
the call to elasticsearchTemplate.multiSearch failed at runtime because of the incompatibility as you said.
So now I have to replace 
```java
NativeSearchQueryBuilder().withQuery(MyUtilitiesES.getQuery(individu)).withSourceFilter(SOURCE_FILTER).build()
queries.add(query);
```
with the appropriate QueryBuilder. Is that right ? I searched for an example or tutorial to do so but nothing came for NativeQuery. I don't see yet how to replace  NativeSearchQueryBuilder().withQuery(someQueryBuilder) with the approriate NativeQuery.
Thank a lot for your response !

**Comment by sothawo** [comment]
As I wrote, you cannot use the `NativeSearchQuery` with the new client, you will need to create instance of `NativeQuery` which you can create with `NativeQueryBuilder`.

`NativeQueryBuilder` has two methods named `withQuery()`, the first takes a `co.elastic.clients.elasticsearch._types.query_dsl.Query` as parameter, the second a builder function for such a query. Like you did in the old version, where you used Elasticsearch's query builders that came from the old now deprecated library, you now need to build Elasticsearch queries using the new client library.

To see how t build queries with the new client libraries, check the documentation from Elasticsearch (https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/searching.html), this page show examples how to build a query.

The tests in Spring Data Elasticsearch have many places where the withQuery() method is used and which you can use as an example: 

<img width="595" alt="image" src="https://user-images.githubusercontent.com/8456476/208447091-fa18e0ee-f222-403f-8387-1a1b84873d4d.png">

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by slide2009** [comment]
Thank you very much ! We are going to look at the ressources you provided.
