### ISSUE TITLE
Missing required property 'UpdateRequest.id'

### ISSUE THREAD

**Issue by wang-xiaowu** [spring-projects/spring-data-elasticsearch#2501]
version: 5.0.4
springboot: 3.0.4

code:
```java
Query query = NativeQuery.builder()
        .withQuery(QueryBuilders.matchAllQueryAsQuery())
        .build();
UpdateQuery updateQuery = UpdateQuery.builder(query)
        .withScriptType(ScriptType.INLINE)
        .withLang("painless")
        .withScript("ctx._source[params.field]=params.val;")
        .withParams(Map.of("field", "author", "val", "测试"))
        .withAbortOnVersionConflict(true)
        .withScriptedUpsert(true)
        .build();
elasticsearchOperations.update(updateQuery, elasticsearchOperations.getIndexCoordinatesFor(TestModel.class));
```

exception:
```java
co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'UpdateRequest.id'

	at co.elastic.clients.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:76)
	at co.elastic.clients.elasticsearch.core.UpdateRequest.<init>(UpdateRequest.java:134)
	at co.elastic.clients.elasticsearch.core.UpdateRequest.<init>(UpdateRequest.java:67)
	at co.elastic.clients.elasticsearch.core.UpdateRequest$Builder.build(UpdateRequest.java:734)
	at co.elastic.clients.elasticsearch.core.UpdateRequest$Builder.build(UpdateRequest.java:402)
	at co.elastic.clients.elasticsearch.core.UpdateRequest.of(UpdateRequest.java:155)
	at org.springframework.data.elasticsearch.client.elc.RequestConverter.documentUpdateRequest(RequestConverter.java:885)
	at org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate.update(ElasticsearchTemplate.java:185)
```

i must set id with UpdateQuery.builder, 
what i want is update the data with script and query

**Comment by wang-xiaowu** [comment]
maybe i should use ApiTypeHelper to disable Required Properties Check
like
```java
try (ApiTypeHelper.DisabledChecksHandle disabledChecksHandle = ApiTypeHelper.DANGEROUS_disableRequiredPropertiesCheck(true)) {}
```

**Comment by wang-xiaowu** [comment]
and another question
if my elasticsearch's version is 7.14
whether or not i can use springboot3?

**Comment by wang-xiaowu** [comment]
add dsl comment
```dsl
POST /book/_update_by_query
{
  "query": {
    "match_all": {}
  }, 
  "script": {
    "params": {
      "val": "测试",
      "field": "author"
    },
    "lang": "painless",
    "source": "ctx._source[params.field]=params.val;"
  }
}
```

**Comment by sothawo** [comment]
The correct method to use is
`ElasticsearchOperations#updateByQuery(UpdateQuery updateQuery, IndexCoordinates index);`

**Comment by sothawo** [comment]
> and another question
> if my elasticsearch's version is 7.14
> whether or not i can continue using the 5.0.3 (version of spring-data-elasticsearch)?

You can still configure the old deprecated client to be used. this will be removed in 5.1 and no active development is done for code using this deprecated feature. 
Wether the new client from Elasticsearch works/keeps working with 7.14 I don't know, that's a question for Elasticsearch to answer.

**Comment by wang-xiaowu** [comment]
yes, i just found it, sorry to bother and thanks for your answer
