### ISSUE TITLE
reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.core.Exceptions$OverflowException: Could not emit buffer due to lack of requests

### ISSUE THREAD

**Issue by patpatpat123** [spring-projects/spring-data-elasticsearch#2508]
Hello team,

Currently using spring-data-elasticsearch 5.1.0-M3, I am observing this issue reproducible 100% while doing saveAll on a Flux.

```
reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.core.Exceptions$OverflowException: Could not emit buffer due to lack of requests
Caused by: reactor.core.Exceptions$OverflowException: Could not emit buffer due to lack of requests
	at reactor.core.Exceptions.failWithOverflow(Exceptions.java:249)
	at reactor.core.publisher.FluxBufferTimeout$BufferTimeoutSubscriber.flushCallback(FluxBufferTimeout.java:227)
	at reactor.core.publisher.FluxBufferTimeout$BufferTimeoutSubscriber.lambda$new$0(FluxBufferTimeout.java:158)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Minimal reproducible snippet:

```
public Flux<Foo> myFlux() {
        Sinks.Many<Foo> sink = Sinks.many().unicast().onBackpressureBuffer();

        int min = 1;
        int max = 3;

        // Generate a random number between min and max
        Random r = new Random();
        int randomNumber = r.nextInt((max - min) + 1) + min;

        Flux<Foo> createCommandFlux = Flux.interval(Duration.ofMillis(randomNumber))
                .map(i -> {

                    Foo onePojo = new Foo(LocalDateTime.now().toEpochSecond(ZoneOffset.UTC), String.valueOf(i));
                    return onePojo;

                });

        createCommandFlux
                .bufferTimeout(500, Duration.ofMillis(200))//tried many values for maxSize and maxTime
                .subscribe(new Subscriber<>() {
                    private Subscription subscription;
                    volatile boolean upstreamComplete = false;

                    @Override
                    public void onSubscribe(Subscription subscription) {
                        this.subscription = subscription;
                        subscription.request(1);
                    }

                    @Override
                    public void onNext(List<Foo> foos) {
                        reactiveElasticRepository.saveAll(foos)
                                .map(sink::tryEmitNext)
                                .doOnComplete(() -> {
                                    if (!upstreamComplete) {
                                        subscription.request(1);
                                    } else {
                                        sink.tryEmitComplete();
                                    }
                                })
                                .subscribe();
                    }

                    @Override
                    public void onError(Throwable throwable) {
                        throwable.printStackTrace();
                        System.err.println("I am able to reproduce this issue 100% " + throwable.getLocalizedMessage());
                        subscription.cancel();
                        sink.tryEmitError(throwable);
                    }

                    @Override
                    public void onComplete() {
                        upstreamComplete = true;
                    }
                });

        return sink.asFlux();
    }
```

An example with a **steady** flux will **not** reproduce the issue.
The flux needs to be (very fast) and the rythm very chaotic.
Run on slow hardware, the issue has less likelyhood to happen pr our testing. The faster the machine, the more and quicker this issue occurs.

The reason is due to the backpressure mechanism for .bufferX methods.

Related PR: https://github.com/reactor/reactor-core/pull/3332

Can Spring Data Elastic team propose a workaround in the meanwhile please?

Thank you

**Comment by sothawo** [comment]
As you wrote, the issue you see is not in Spring Data Elasticsearch but in reactor, so there is nothing for us to do here.
You could implement your own kind of buffering data from a flux before passing it on
