### ISSUE TITLE
@Document(indexName = "index", createIndex = true) fails with index already exists, although definition unchanged

### ISSUE THREAD

**Issue by slow-turtle** [spring-projects/spring-data-elasticsearch#2535]
`@Document(indexName = "index", createIndex = true)`

Annotation on entity class fails on **second** application startup with "index already exists", although the document **definition** is **unchanged**.
Omitting parameter createIndex has the same effect.

Mappings are defined by **field annotations**.

Spring Data Elasticsearch version: 5.0.3
Dependency is: spring-boot-starter-data-elasticsearch (3.0.5)
Elasticsearch version: 8.6.2

Caused by: co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/indices.create] failed: [resource_already_exists_exception] index [... my index name ...] already exists
	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:282) ~[elasticsearch-java-8.5.3.jar:na]
	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:148) ~[elasticsearch-java-8.5.3.jar:na]
	at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.create(ElasticsearchIndicesClient.java:266) ~[elasticsearch-java-8.5.3.jar:na]
	at org.springframework.data.elasticsearch.client.elc.IndicesTemplate.lambda$doCreate$0(IndicesTemplate.java:138) ~[spring-data-elasticsearch-5.0.3.jar:5.0.3]
	at org.springframework.data.elasticsearch.client.elc.ChildTemplate.execute(ChildTemplate.java:71) ~[spring-data-elasticsearch-5.0.3.jar:5.0.3]

**Comment by sothawo** [comment]
Are you creating the index yourself by calling `IndexOperations.create()`? The annotation value is only considered when the application starts and uses Spring Data Elasticsearch repositories.

**Comment by slow-turtle** [comment]
Elasticsearch running on a server. Permissions to create, read, write and check available.
[Stacktrace.txt](https://github.com/spring-projects/spring-data-elasticsearch/files/11311552/Stacktrace.txt)

**Comment by sothawo** [comment]
Do you use the same entity class in different repositories? Or the same index name for different entity classes?

**Comment by slow-turtle** [comment]
One entity class is used for one repository.
Possibly the problem is related to the client configuration in an environment where a proxy is between the server and the client.
For index creation this seems to be no problem, possibly because retries could make it happen.
The exist check possibly fails because credentials or proxy settings are not passed.
Please find attached my really trivial project source.
[src.zip](https://github.com/spring-projects/spring-data-elasticsearch/files/11320090/src.zip)

**Comment by sothawo** [comment]
The proxy and authorization is no problem, I run this often in the integration tests and test application with an intercepting proxy between and my local Elasticsearch always runs with authorization; I just omit the ssl.

I ran your sample project with Spring Boot 3.0.6 against a Elasticsearch 8.6.2 with this adapted config:

```java
@Configuration
public class ElasticsearchConfig extends ElasticsearchConfiguration {

    @Override
    public ClientConfiguration clientConfiguration() {
        return ClientConfiguration.builder()
                .connectedTo("localhost:9200")
//                .usingSsl()
                .withBasicAuth("elastic", "******")
                .withProxy("localhost:8080")
                .withClientConfigurer(ElasticsearchClients.ElasticsearchRestClientConfigurationCallback.from(restClientBuilder -> {
                    return restClientBuilder;
                }))
                .build();
    }

}
```

Below is a screenshot of the intercepting proxy: The first two entries are the first _exists_ with the following _create_, the third is the second _exists_ and then there is no more _create_. So all works as it should.

<img width="1297" alt="Screenshot 2023-04-25 at 13 30 11" src="https://user-images.githubusercontent.com/8456476/234263614-0403013a-7027-46f2-83cd-272ac444b7ba.png">

**Comment by sothawo** [comment]
When omitting the ssl config, did you disable SSL in the server as well? I omitted the ssl configuration setting because my Elasticsearch is configured to not use ssl. But that has nothing to do with your problem.

Can you skip the proxy and connect directly to Elasticsearch? Or can you check the traffic that is passing through your proxy?

With the code you provided, this is not reproducable for me.

**Comment by slow-turtle** [comment]
Thanks for the support! Will investigate later.
