### ISSUE TITLE
spring-data-elasticsearch:4.4.10   IndicesBoost  error

### ISSUE THREAD

**Issue by freedally** [spring-projects/spring-data-elasticsearch#2598]
spring-data-elasticsearch:4.4.10
```java
    List<IndexBoost> indexBoosts = new ArrayList<>();
    indexBoosts.add(new IndexBoost(IndexConst.INDEX_NAME_1, 2));
    indexBoosts.add(new IndexBoost(IndexConst.INDEX_NAME_2, 1));


    Pageable pageable = PageRequest.of(0, 10);

    NativeQuery nativeQuery = NativeQuery.builder()
            .withIndicesBoost(indexBoosts)
            .withQuery(query)
            .withPageable(pageable).build();

    SearchHits<EntityAsMap> searchHits = elasticsearchTemplate.search(nativeQuery, EntityAsMap.class, IndexCoordinates.of(IndexConst.INDEX_NAME_1, IndexConst.INDEX_NAME_2));
```

Received exception

```shell
Caused by: co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/search] failed: [parsing_exception] Expected [END_OBJECT] in [indices_boost] but found [FIELD_NAME]
	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:313)
	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:153)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1754)
	at org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate.lambda$search$14(ElasticsearchTemplate.java:312)
	at org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate.execute(ElasticsearchTemplate.java:514)
	... 71 more
```
Is my method incorrect?

There seems to be an error here：org.springframework.data.elasticsearch.client.elc.RequestConverter 

```java
// line 1206
if (!isEmpty(query.getIndicesBoost())) {
    Map<String, Double> boosts = new LinkedHashMap<>();
    query.getIndicesBoost().forEach(indexBoost -> {
        boosts.put(indexBoost.getIndexName(), (double) indexBoost.getBoost());
    });
    // noinspection unchecked
    builder.indicesBoost(boosts);
}

```

**Comment by sothawo** [comment]
You are using the new client, what version is the server? If it is an Elasticsearch 8 server, do you set the compatibility headers?

4.4.x is out of maintenance now, can you try this with the current version (5.1)

**Comment by freedally** [comment]
elasticsearch version：7.17.8

I upgraded my dependencies：
spring-boot-starter-data-elasticsearch：3.1.1
spring-data-elasticsearch：5.1.1

I got the same result.
I set boosts to an array during debugging and got the correct result.
```java
if (!isEmpty(query.getIndicesBoost())) {
  Map<String, Double> boosts = new LinkedHashMap<>();
  query.getIndicesBoost()
	  .forEach(indexBoost -> boosts.put(indexBoost.getIndexName(), (double) indexBoost.getBoost()));
  // noinspection unchecked
  builder.indicesBoost(boosts);
}
```

**Comment by sothawo** [comment]
> I set boosts to an array during debugging and got the correct result.

what do you mean with that, where do you change?

**Comment by freedally** [comment]
I got the correct result after making the modifications like this.
org.springframework.data.elasticsearch.client.elc.RequestConverter

```java
  // line 1414
  if (!isEmpty(query.getIndicesBoost())) {
	  List<Map<String, Double>> boosts = query.getIndicesBoost().stream()
			  .map(indexBoost -> Map.of(indexBoost.getIndexName(), (double) indexBoost.getBoost()))
			  .collect(Collectors.toList());
  
	  // noinspection unchecked
	  builder.indicesBoost(boosts);
  }
```

**Comment by sothawo** [comment]
Just had a closer look at the Elasticsearch client and the API definition. So it seems that the we need to send an array of objects that just have one property (index name) and value.

I thought that the client would send the entries from the map as an array of such objects, but here the `Map` seems only to be used to represent an object with a property whose name is not known beforehand.

So switching from one Map with many values to a list of maps with one value each is correct. Thanks for finding that.

I'll fix that later today.
