### ISSUE TITLE
ES server not compatible with elastic search spring data 

### ISSUE THREAD

**Issue by bhattarvy** [spring-projects/spring-data-elasticsearch#2701]
`2023-09-17 09:18:25.032 ERROR 1 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.elasticsearch.UncategorizedElasticsearchException: Invalid or missing build flavor [oss]; nested exception is ElasticsearchException[Invalid or missing build flavor [oss]]] with root cause

org.elasticsearch.ElasticsearchException: Invalid or missing build flavor [oss]
	at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2084) ~[elasticsearch-rest-high-level-client-7.15.2.jar!/:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1732) ~[elasticsearch-rest-high-level-client-7.15.2.jar!/:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1702) ~[elasticsearch-rest-high-level-client-7.15.2.jar!/:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1672) ~[elasticsearch-rest-high-level-client-7.15.2.jar!/:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1128) ~[elasticsearch-rest-high-level-client-7.15.2.jar!/:7.15.2]
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.lambda$search$11(ElasticsearchRestTemplate.java:317) ~[spring-data-elasticsearch-4.3.9.jar!/:4.3.9]
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:408) ~[spring-data-elasticsearch-4.3.9.jar!/:4.3.9]
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.search(ElasticsearchRestTemplate.java:317) ~[spring-data-elasticsearch-4.3.9.jar!/:4.3.9]
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.search(AbstractElasticsearchTemplate.java:410) ~[spring-data-elasticsearch-4.3.9.jar!/:4.3.9]
	at com.bpss.essservice.repository.es.EmployeeSearch.finAll(EmployeeSearch.java:24) ~[classes!/:0.0.1-SNAPSHOT]
	at com.bpss.essservice.controller.TestController.getFromES(TestController.java:49) ~[classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_342]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_342]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_342]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_342]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.23.jar!/:5.3.23]

`

I tried downgrading the spring-data-elastic search version to 4.2.6 still the same issue
ES server version - "7.10.2"

**Comment by sothawo** [comment]
I don't know what you refer to with "ES Server"; this error messages were introduced by Elasticsearch if I remember correctly with client version 7.10.

Elasticsearch version 7.10 is pretty old anyway, so is Spring Data Elasticsearch 4.2.

Spring Data Elasticsearch is built and tested against Elasticsearch servers, not other implementations. You might check if [Spring Data Opensearch](https://github.com/opensearch-project/spring-data-opensearch) which is built upon Spring Data Elasticsearch works for you.

**Comment by bhattarvy** [comment]
ES Server I mean the elastic search version which is 7.10.

I tried using Spring Data Open search but it does not work with Java8 and we can not change the java version.

Also with Spring Data Elasticsearch 4.2, it gives the build flavor error I mentioned above.

is there any possible way to fix this?

**Comment by sothawo** [comment]
> is there any possible way to fix this?

none that I know of.

Java 8 is almost ten years old and long out of support. Even the next LTS version, 11, will reach end of non-paid support this month. 
As a software developer and consultant (which is what is my profession), and not as Spring Data Elasticsearch maintainer I'd strongly recommend that you update your environments and software.
