### ISSUE TITLE
Criteria API issue with nested and object fields in one query

### ISSUE THREAD

**Issue by koha26** [spring-projects/spring-data-elasticsearch#2773]
Hi, I am working on some dynamic logic to create a query for Elastic Search. I decided to use Criteria API, however, it builds very strange and complex queries. Below I will try to describe problematic and bug that I found.

My classes:
`
@Document(indexName = "model")
@TypeAlias("model")
public class Model {
    @Id
    private String id;
    //...
   @Field(type = FieldType.Object)
   private User owner;
   @Field(type = FieldType.Nested)
    private List<Task> tasks;
}

@Document(indexName = "task")
@TypeAlias("task")
public class Task {
    @Id
    private String id;
    //...
   @Field(type = FieldType.Object)
   private User creator;
   @Field(type = FieldType.Nested)
    private List<SubTask> subTasks;
}

public class SubTask {
    @Id
    private String id;
    //...
   @Field(type = FieldType.Object)
   private User assignee;
   @Field(type = FieldType.Boolean)
   private boolean done;
}

public class User {
    @Id
    private String login;
    //...
   @Field(type = FieldType.Keyword)
   private String login;
}
`

How do I build the next query "select all models where tasks.subTasks.assignee.login = 'user1' and tasks.subTasks.done = 'true' ":
`
Criteria.where('tasks.subTasks.done').is(true).subCriteria(Criteria.where('tasks.subTasks.assignee.login.keyword').is('user1'))
`

As a result, it generates the next query:
{"from":0,"query":{"bool":{"must":[{"nested":{"path":"tasks.subTasks","query":{"query_string":{"default_operator":"and","fields":["tasks.subTasks.done"],"query":"true"}},"score_mode":"avg"}},{"bool":{"must":[{"nested":{"path":"tasks.subTasks.assignee","query":{"query_string":{"default_operator":"and","fields":["tasks.subTasks.assignee.login.keyword"],"query":"user1"}},"score_mode":"avg"}}]}}]}},"size":15,"track_scores":false,"version":true}

And it throws an exception:
`
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.elasticsearch.UncategorizedElasticsearchException: [es/search] failed: [search_phase_execution_exception] all shards failed; nested exception is co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/search] failed: [search_phase_execution_exception] all shards failed] with root cause
co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/search] failed: [search_phase_execution_exception] all shards failed
	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:337)
	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:155)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1754)
	at org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate.lambda$search$14(ElasticsearchTemplate.java:312)
	at org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate.execute(ElasticsearchTemplate.java:514)
	at org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate.search(ElasticsearchTemplate.java:312)
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.search(AbstractElasticsearchTemplate.java:418)
`

I expect that Criteria API will generate the following query that works:
`
GET model/_search
{
  "query": {
    "nested": {
      "path": "tasks",
      "query": {
        "nested": {
          "path": "tasks.subTasks",
          "query": {
            "bool": {
              "must": [
                { "match": { "tasks.subTasks.done": "true" } },
                { "match": { "tasks.subTasks.assignee.login": "user1" } }
              ]
            }
          }
        }
      }
    }
  }
}
` 

Is there any opportunity to build queries with nested objects using Criteria API? Or do I need to use only Nested Query?

**Comment by sothawo** [comment]
Please create a minimal project reproducing this issue and provide it on GitHub or Codeberg or pack it up as zip.

**Comment by koha26** [comment]
You can find an example in the following test project: [spring-data-elasticsearch-2773.zip](https://github.com/spring-projects/spring-data-elasticsearch/files/13400354/spring-data-elasticsearch-2773.zip).

I just quickly tried to simulate running queries. To run an example: 
1) Open docker folder and run `docker-compose up`
2) Open SearchServiceImplTest and run tests

Hope it helps. Thank you in advance.
