### ISSUE TITLE
NPE in CriteriaFilterProcessor, can't use .not() and .and()

### ISSUE THREAD

**Issue by clapointe** [spring-projects/spring-data-elasticsearch#2838]
So I have a project with documents in it and I want to get them according to an id field and whether they have been "soft-deleted".

Here is my code:
```
var criteria = new Criteria();
criteria.and(new Criteria("subject.documentId").is(search.getDocumentId()));
criteria.and(new Criteria("audit.deletedBy.id").not().exists());

var query = new CriteriaQuery(criteria).setPageable(pageable);
var searchHits = elasticsearchOperations.search(query, getEntityClass(), readIndex);
```

Here is the exception:
```
[2024-01-29 09:45:24,337] [http-nio-8091-exec-3] ERROR c.l.p.c.RestExceptionHandler - {traceId=65b765a4fae77a1f5e070490e3b793af, spanId=a3c5fb849def54f7, user_id=7179047f-726c-4441-9146-25700f233d68} Unhandled exception : 
java.lang.NullPointerException: Cannot invoke "org.springframework.data.elasticsearch.core.query.Field.getName()" because the return value of "org.springframework.data.elasticsearch.core.query.Criteria.getField()" is null
	at org.springframework.data.elasticsearch.client.elc.CriteriaFilterProcessor.createQuery(CriteriaFilterProcessor.java:75)
	at org.springframework.data.elasticsearch.client.elc.RequestConverter.addFilter(RequestConverter.java:1480)
	at org.springframework.data.elasticsearch.client.elc.RequestConverter.searchRequest(RequestConverter.java:1044)
	at org.springframework.data.elasticsearch.client.elc.RequestConverter.searchRequest(RequestConverter.java:1024)
	at org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate.search(ElasticsearchTemplate.java:322)
```

Here is where I think the problem is:
```
// CriteriaFilterProcessor
for (Criteria chainedCriteria : criteria.getCriteriaChain()) {
	if (chainedCriteria.isOr()) {
		BoolQuery.Builder boolQueryBuilder = QueryBuilders.bool();
		queriesForEntries(chainedCriteria).forEach(boolQueryBuilder::should);
		filterQueries.add(new Query(boolQueryBuilder.build()));
	} else if (chainedCriteria.isNegating()) {
		Collection<? extends Query> negatingFilters = buildNegatingFilter(criteria.getField().getName(),
				criteria.getFilterCriteriaEntries());
		filterQueries.addAll(negatingFilters);
	} else {
		filterQueries.addAll(queriesForEntries(chainedCriteria));
	}
}
```

My question is: why do we use `criteria` and not `chainedCriteria` in that `else if`?

Things seem to work as expected without the `.not()`

**Comment by sothawo** [comment]
Multiple problems in your code:

* You are specifying 3 `Criteria` objects. But for the first one `var criteria = new Criteria()` you don't specify for which field it should be and what condition is should satisfy. It's an empty `Citeria` specification
* When calling `and()` on a `Criteria` the function returns a new or modified `Criteria` instance (checvk the API documentation). But you discard this and call `and` on the first one again.

Without having the time to run a test this should work:
```
var criteria = Criteria
  .where("subject.documentId").is(search.getDocumentId())
  .and("audit.deletedBy.id").not().exists();

var query = new CriteriaQuery(criteria).setPageable(pageable);
var searchHits = elasticsearchOperations.search(query, getEntityClass(), readIndex);```

**Comment by clapointe** [comment]
Thank you so much! I used to have a series of ```criteria = criteria.and(…)``` but after looking at the code and seeing it returned `this` I thought I could remove the re-assigning. 
And I was treating the field-less Criteria as if it was an "and" operator, basically. It did work as long as I only had `is` or `exist` conditions without negation, so I didn't realize it wasn't correct.

My new code looks like this, I still have an empty Criteria for now because it seems to work… if this is bad practice I'll rearrange it further.
```
var criteria = new Criteria();
if (search.getDocumentId() != null) {
    criteria = criteria.and("subject.documentId").is(search.getDocumentId());
}
if (search.getDeleted() != null) {
    if (search.getDeleted()) {
        criteria = criteria.and("audit.deletedBy.id").exists();
    } else {
        criteria = criteria.and("audit.deletedBy.id").not().exists();
    }
}
```
