### ISSUE TITLE
elasticsearchRestTemplate.search occur SocketTimeoutException under concurrent condition everytime

### ISSUE THREAD

**Issue by ilwyiworld** [spring-projects/spring-data-elasticsearch#2868]
**spring-data-elasticsearch:4.2.5**

**elasticsearch:7.12.1**

when I use _elasticsearchRestTemplate.search_ to search data under concurrent condition everytime(tested by JMETER),only a few request return data successful,others occur SocketTimeoutException,here is exception trace:
```
Caused by: java.lang.RuntimeException: 1,500 milliseconds timeout on connection http-outgoing-21 [ACTIVE]
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.translateException(ElasticsearchRestTemplate.java:400)
	... 92 more
Caused by: java.net.SocketTimeoutException: 1,500 milliseconds timeout on connection http-outgoing-21 [ACTIVE]
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:865)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:283)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1654)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1624)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1594)
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1110)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.lambda$search$11(ElasticsearchRestTemplate.java:296)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:383)
	... 91 more
Caused by: java.net.SocketTimeoutException: 1,500 milliseconds timeout on connection http-outgoing-21 [ACTIVE]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	... 1 more

```
here is JMETER setting:
<img width="1534" alt="1" src="https://github.com/spring-projects/spring-data-elasticsearch/assets/7789175/dea26f8c-4653-46f7-bc1b-566f46e43fd3">
<img width="1557" alt="2" src="https://github.com/spring-projects/spring-data-elasticsearch/assets/7789175/69b7ce7e-b896-4f36-8d9d-caaf3ad1f56a">
<img width="1545" alt="3" src="https://github.com/spring-projects/spring-data-elasticsearch/assets/7789175/b44b00e1-7439-4a50-8072-5f5e6e1f4238">

here is java code:
```java
    public Resp testGetEsData() {
        // 随机查询数据
        BoolQueryBuilder filter = QueryBuilders.boolQuery();
        filter.must(QueryBuilders.termsQuery("allLabels", Lists.newArrayList("历史","地理")));
        filter.must(QueryBuilders.termsQuery("questionType", Lists.newArrayList(0)));
        filter.must(QueryBuilders.termsQuery("questionSpecifyType", Lists.newArrayList(2)));
        // 算法不推荐限制
        filter.mustNot(QueryBuilders.termsQuery("algorithmParams", Lists.newArrayList("notShow")));
        NativeSearchQueryBuilder searchQueryBuilder = new NativeSearchQueryBuilder();
        Script script = new Script("Math.random()");
        ScriptSortBuilder sortBuilder = new ScriptSortBuilder(script, ScriptSortBuilder.ScriptSortType.NUMBER);
        searchQueryBuilder.withSort(sortBuilder);
        searchQueryBuilder.withPageable(PageRequest.of(0, 1));
        NativeSearchQuery query = searchQueryBuilder.build();
        SearchHits<CompleteQuestionEntity> searchHits = elasticsearchRestTemplate.search(query, CompleteQuestionEntity.class);
        Page<CompleteQuestionEntity> page = PageableExecutionUtils.getPage(searchHits.getSearchHits().stream()
                .map(SearchHit::getContent).collect(Collectors.toList()), PageRequest.of(0, 1), searchHits::getTotalHits);
        return Resp.success(page.getContent().get(0));
    }
```

but when I send same request to es directly used by JMETER,it all worked successfully,here is JMETER setting:
<img width="1509" alt="4" src="https://github.com/spring-projects/spring-data-elasticsearch/assets/7789175/59caf3c1-88d3-4171-ad97-7c9d75896e3d">
<img width="1509" alt="5" src="https://github.com/spring-projects/spring-data-elasticsearch/assets/7789175/7911acf9-8b05-4f95-8472-e8ab084d3295">
<img width="1528" alt="6" src="https://github.com/spring-projects/spring-data-elasticsearch/assets/7789175/a16b597d-3d94-437f-92b3-5247a2406219">

here is request body:
```json
{
	"query": {
		"bool": {
			"must": [
				{
					"terms": {
						"allLabels": [
							"历史",
							"地理"
						],
						"boost": 1
					}
				},
				{
					"terms": {
						"questionType": [
							0
						],
						"boost": 1
					}
				},
				{
					"terms": {
						"questionSpecifyType": [
							2
						],
						"boost": 1
					}
				}
			],

			"must_not": [
				{
					"terms": {
						"algorithmParams": [
							"notShow"
						],
						"boost": 1
					}
				}
			],
			"adjust_pure_negative": true,
			"boost": 1
		}
	},
	"sort": {
		"_script": {
			"script": {
				"source": "Math.random()",
				"lang": "painless"
			},
			"type": "number",
			"order": "asc"
		}
	}
	"from": 0,
	"size": 1
}
``` 

here is spring-data-elasticsearch config:
```
spring:
  elasticsearch:
    rest:
      uris: 192.168.102.57:9200
      username:
      password:
      connection-timeout: 1500
      read-timeout: 1500
      max-conn-total: 800
      max-conn-per-route: 800
      keep-alive-minutes: 10
      sniffer:
        interval: 5m
        delay-after-failure: 1m
```
is it something wrong with those config?

**Comment by sothawo** [comment]
4.2 is out of maintenance for nearly 2 years now. If we should have a look, update to maintained version (>= 5.1)
